language: php

php: [5.3.3, 5.3, 5.4, 5.5]

before_script:
  - composer selfupdate
  - composer install --prefer-source
  - printf "\n" | pecl install pecl_http

script:
  - bin/phpspec run
  - bin/phpcs --standard=PSR1 --report=summary -n src/
  - bin/phpcs --standard=PSR2 --report=summary -n src/